/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MercyRouteImport } from './routes/mercy'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MercyIndexRouteImport } from './routes/mercy.index'
import { Route as MercyWorkRouteImport } from './routes/mercy.work'
import { Route as MercyAboutRouteImport } from './routes/mercy.about'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MercyRoute = MercyRouteImport.update({
  id: '/mercy',
  path: '/mercy',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MercyIndexRoute = MercyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MercyRoute,
} as any)
const MercyWorkRoute = MercyWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => MercyRoute,
} as any)
const MercyAboutRoute = MercyAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MercyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/design': typeof DesignRoute
  '/mercy': typeof MercyRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writing': typeof WritingRoute
  '/mercy/about': typeof MercyAboutRoute
  '/mercy/work': typeof MercyWorkRoute
  '/mercy/': typeof MercyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/design': typeof DesignRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writing': typeof WritingRoute
  '/mercy/about': typeof MercyAboutRoute
  '/mercy/work': typeof MercyWorkRoute
  '/mercy': typeof MercyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/design': typeof DesignRoute
  '/mercy': typeof MercyRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/writing': typeof WritingRoute
  '/mercy/about': typeof MercyAboutRoute
  '/mercy/work': typeof MercyWorkRoute
  '/mercy/': typeof MercyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/design'
    | '/mercy'
    | '/sitemap.xml'
    | '/writing'
    | '/mercy/about'
    | '/mercy/work'
    | '/mercy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/design'
    | '/sitemap.xml'
    | '/writing'
    | '/mercy/about'
    | '/mercy/work'
    | '/mercy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/design'
    | '/mercy'
    | '/sitemap.xml'
    | '/writing'
    | '/mercy/about'
    | '/mercy/work'
    | '/mercy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DesignRoute: typeof DesignRoute
  MercyRoute: typeof MercyRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WritingRoute: typeof WritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercy': {
      id: '/mercy'
      path: '/mercy'
      fullPath: '/mercy'
      preLoaderRoute: typeof MercyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercy/': {
      id: '/mercy/'
      path: '/'
      fullPath: '/mercy/'
      preLoaderRoute: typeof MercyIndexRouteImport
      parentRoute: typeof MercyRoute
    }
    '/mercy/work': {
      id: '/mercy/work'
      path: '/work'
      fullPath: '/mercy/work'
      preLoaderRoute: typeof MercyWorkRouteImport
      parentRoute: typeof MercyRoute
    }
    '/mercy/about': {
      id: '/mercy/about'
      path: '/about'
      fullPath: '/mercy/about'
      preLoaderRoute: typeof MercyAboutRouteImport
      parentRoute: typeof MercyRoute
    }
  }
}

interface MercyRouteChildren {
  MercyAboutRoute: typeof MercyAboutRoute
  MercyWorkRoute: typeof MercyWorkRoute
  MercyIndexRoute: typeof MercyIndexRoute
}

const MercyRouteChildren: MercyRouteChildren = {
  MercyAboutRoute: MercyAboutRoute,
  MercyWorkRoute: MercyWorkRoute,
  MercyIndexRoute: MercyIndexRoute,
}

const MercyRouteWithChildren = MercyRoute._addFileChildren(MercyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DesignRoute: DesignRoute,
  MercyRoute: MercyRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WritingRoute: WritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
